"""add user metadata

Revision ID: 237016e9f263
Revises: ad3bf20938ce
Create Date: 2019-06-23 14:03:52.550883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237016e9f263'
down_revision = 'ad3bf20938ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_user_name'), 'players', ['user_name'], unique=False)
    op.add_column('users', sa.Column('added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added')
    op.drop_index(op.f('ix_players_user_name'), table_name='players')
    op.drop_column('players', 'user_name')
    # ### end Alembic commands ###
