"""index rate snapshot

Revision ID: 8413043d0c62
Revises: 237016e9f263
Create Date: 2019-09-14 02:54:42.573963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8413043d0c62'
down_revision = '237016e9f263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_rate_snapshot'), 'players', ['rate_snapshot'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_rate_snapshot'), table_name='players')
    # ### end Alembic commands ###
