"""cascades

Revision ID: 909007addd43
Revises: a1d082f7c1f2
Create Date: 2019-10-06 14:45:19.424646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909007addd43'
down_revision = 'a1d082f7c1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_match_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'players', ['match_id', 'owner_number'], ['match_id', 'number'], ondelete='cascade')
    op.drop_constraint('players_match_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'teams', ['match_id', 'team_id'], ['match_id', 'team_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_match_id_fkey', 'players', 'teams', ['match_id', 'team_id'], ['match_id', 'team_id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_match_id_fkey', 'files', 'players', ['match_id', 'owner_number'], ['match_id', 'number'])
    # ### end Alembic commands ###
