"""add index on rate_after

Revision ID: a1d082f7c1f2
Revises: 650e62b5206c
Create Date: 2019-09-22 15:37:44.434821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d082f7c1f2'
down_revision = '650e62b5206c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_rate_after'), 'players', ['rate_after'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_rate_after'), table_name='players')
    # ### end Alembic commands ###
