"""add user indices

Revision ID: ad3bf20938ce
Revises: 0816c22f8668
Create Date: 2019-05-01 19:40:09.228235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3bf20938ce'
down_revision = '0816c22f8668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_civilization_id'), 'players', ['civilization_id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_civilization_id'), table_name='players')
    # ### end Alembic commands ###
