"""index played date and language

Revision ID: b13aecf90b4e
Revises: 8413043d0c62
Create Date: 2019-09-14 18:01:56.786993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13aecf90b4e'
down_revision = '8413043d0c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_language'), 'files', ['language'], unique=False)
    op.create_index(op.f('ix_matches_played'), 'matches', ['played'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_played'), table_name='matches')
    op.drop_index(op.f('ix_files_language'), table_name='files')
    # ### end Alembic commands ###
